library(testthat)
library(mutate.with.erroR)

test_check("mutate.with.erroR")
